### ISSUE TITLE
Cell SubViews Animations are Off

### ISSUE THREAD

**Issue by unrevised6419** [ashfurrow/UICollectionViewFlowLayoutExample#1]
Try to add in cell a UILabel with constraints to top, left, right.
You'll observe that during layout animation, only cell size is animated, the subviews size is changed at beginning without animation, and it looks a bit strange.
Greetings!
Andrew.

**Comment by ashfurrow** [comment]
Hmm interesting. Can you upload a sample project demonstrating the issue for me?

**Comment by unrevised6419** [comment]
I forked your project and made some changes to notice the issue.
https://github.com/thendrluca/UICollectionViewFlowLayoutExample
But I think this a SDK/API issue.

**Comment by ashfurrow** [comment]
Very interesting. Have you filed a bug report with Apple that I can duplicate? Do you think this issue ought to be closed, or remain open?

**Comment by unrevised6419** [comment]
No, unfortunately I didn't filled a bug report.
I think issue must be open, maybe someone found a solution and have an answer for us :smile:
